# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(672, 427)
        MainWindow.setToolTipDuration(-1)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.cipher_3x2_Button = QtWidgets.QPushButton(self.frame)
        self.cipher_3x2_Button.setObjectName("cipher_3x2_Button")
        self.verticalLayout.addWidget(self.cipher_3x2_Button)
        self.cipher_3x3_Button = QtWidgets.QPushButton(self.frame)
        self.cipher_3x3_Button.setObjectName("cipher_3x3_Button")
        self.verticalLayout.addWidget(self.cipher_3x3_Button)
        self.decrypt_3x3_Button = QtWidgets.QPushButton(self.frame)
        self.decrypt_3x3_Button.setObjectName("decrypt_3x3_Button")
        self.verticalLayout.addWidget(self.decrypt_3x3_Button)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.brute_force_3x3_Button = QtWidgets.QPushButton(self.frame_2)
        self.brute_force_3x3_Button.setObjectName("brute_force_3x3_Button")
        self.verticalLayout_2.addWidget(self.brute_force_3x3_Button)
        self.gridLayout.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.linear_cipher_3x3_Button = QtWidgets.QPushButton(self.frame_4)
        self.linear_cipher_3x3_Button.setObjectName("linear_cipher_3x3_Button")
        self.verticalLayout_4.addWidget(self.linear_cipher_3x3_Button)
        self.linear_cipher_decrypt_Button = QtWidgets.QPushButton(self.frame_4)
        self.linear_cipher_decrypt_Button.setObjectName("linear_cipher_decrypt_Button")
        self.verticalLayout_4.addWidget(self.linear_cipher_decrypt_Button)
        self.linear_crypt_3x3_Button = QtWidgets.QPushButton(self.frame_4)
        self.linear_crypt_3x3_Button.setObjectName("linear_crypt_3x3_Button")
        self.verticalLayout_4.addWidget(self.linear_crypt_3x3_Button)
        self.gridLayout.addWidget(self.frame_4, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.differential_crypt_3x2_Button = QtWidgets.QPushButton(self.frame_3)
        self.differential_crypt_3x2_Button.setObjectName("differential_crypt_3x2_Button")
        self.verticalLayout_3.addWidget(self.differential_crypt_3x2_Button)
        self.differential_crypt_3x3_Button = QtWidgets.QPushButton(self.frame_3)
        self.differential_crypt_3x3_Button.setObjectName("differential_crypt_3x3_Button")
        self.verticalLayout_3.addWidget(self.differential_crypt_3x3_Button)
        self.gridLayout.addWidget(self.frame_3, 1, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.double_cipher_3x3_Button = QtWidgets.QPushButton(self.frame_5)
        self.double_cipher_3x3_Button.setObjectName("double_cipher_3x3_Button")
        self.verticalLayout_5.addWidget(self.double_cipher_3x3_Button)
        self.double_cipher_decryption_Button = QtWidgets.QPushButton(self.frame_5)
        self.double_cipher_decryption_Button.setObjectName("double_cipher_decryption_Button")
        self.verticalLayout_5.addWidget(self.double_cipher_decryption_Button)
        self.meet_in_the_middle_Button = QtWidgets.QPushButton(self.frame_5)
        self.meet_in_the_middle_Button.setObjectName("meet_in_the_middle_Button")
        self.verticalLayout_5.addWidget(self.meet_in_the_middle_Button)
        self.gridLayout.addWidget(self.frame_5, 2, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setAutoFillBackground(False)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.hard_cipher_Button = QtWidgets.QPushButton(self.frame_6)
        self.hard_cipher_Button.setObjectName("hard_cipher_Button")
        self.verticalLayout_6.addWidget(self.hard_cipher_Button)
        self.differential_crypt_hard_cipher_Button = QtWidgets.QPushButton(self.frame_6)
        self.differential_crypt_hard_cipher_Button.setObjectName("differential_crypt_hard_cipher_Button")
        self.verticalLayout_6.addWidget(self.differential_crypt_hard_cipher_Button)
        self.gridLayout.addWidget(self.frame_6, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 672, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Шифры и методы их криптоанализа"))
        self.label.setText(_translate("MainWindow", "Шифры с S-блоками:"))
        self.cipher_3x2_Button.setText(_translate("MainWindow", "XOR-шифрование с S-блоком 3x2"))
        self.cipher_3x3_Button.setText(_translate("MainWindow", "XOR-шифрование с S-блоком 3x3"))
        self.decrypt_3x3_Button.setText(_translate("MainWindow", "Дешифрование S-блоком 3x3"))
        self.label_2.setText(_translate("MainWindow", "Подбор ключа по открытому и зашифрованному сообщению для S-блока 3x3 (со знанием длины ключа):"))
        self.brute_force_3x3_Button.setText(_translate("MainWindow", "Метод полного перебора"))
        self.label_4.setText(_translate("MainWindow", "Линейный криптоанализ:"))
        self.linear_cipher_3x3_Button.setText(_translate("MainWindow", "Шифрование с линейным S-блоком 3х3"))
        self.linear_cipher_decrypt_Button.setText(_translate("MainWindow", "Дешифрование с линейным S-блоком 3х3"))
        self.linear_crypt_3x3_Button.setText(_translate("MainWindow", "Линейный криптоанализ шифра"))
        self.label_3.setText(_translate("MainWindow", "Дифференциальный криптоанализ простых шифров:"))
        self.differential_crypt_3x2_Button.setText(_translate("MainWindow", "Диф. крипт. XOR-шифра с S-блоком 3x2"))
        self.differential_crypt_3x3_Button.setText(_translate("MainWindow", "Диф. крипт. XOR-шифра с S-блоком 3x3"))
        self.label_5.setText(_translate("MainWindow", "Метод встречи посередине:"))
        self.double_cipher_3x3_Button.setText(_translate("MainWindow", "Двойное шифрование с S-блоками 3x3"))
        self.double_cipher_decryption_Button.setText(_translate("MainWindow", "Дешифрование"))
        self.meet_in_the_middle_Button.setText(_translate("MainWindow", "Метод встречи посередине"))
        self.label_7.setText(_translate("MainWindow", "Дифференциальный криптоанализ шифра с 64-битным ключом и 16 S-блоками 4x3:"))
        self.hard_cipher_Button.setText(_translate("MainWindow", "Шифр с 64-битным ключом"))
        self.differential_crypt_hard_cipher_Button.setText(_translate("MainWindow", "Дифференциальный криптоанализ шифра"))

